global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'stock-api-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'stock-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
